# Robot name goes here
justbot:
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controller 1
  joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    # pid:
    #   p: 100.0
    #   i: 50.0
    #   d: 10.0

  # Controller 2
  joint_2_controller:
    type: effort_controllers/JointPositionController 
    joint: joint_2
    # pid:
    #   p: 100.0
    #   i: 50.0
    #   d: 10.0

  # Controller 3
  joint_3_controller:
    type: effort_controllers/JointPositionController 
    joint: joint_3
    # pid:
    #   p: 100.0
    #   i: 50.0
    #   d: 10.0

  # Controller 4
  joint_4_controller:
    type: effort_controllers/JointPositionController 
    joint: joint_4
    # pid:
    #   p: 100.0
    #   i: 50.0
    #   d: 10.0

  # Controller 5
  joint_5_controller:
    type: effort_controllers/JointPositionController 
    joint: joint_5
    # pid:
    #   p: 100.0
    #   i: 50.0
    #   d: 10.0

  # Controller 6
  joint_6_controller:
    type: effort_controllers/JointPositionController 
    joint: joint_6
    # pid:
    #   p: 100.0
    #   i: 50.0
    #   d: 10.0

  # Tool Controller
  tool_controller:
    type: effort_controllers/JointPositionController 
    joint: tool_joint
    # pid:
    #   p: 40.0
    #   i: 0.0
    #   d: 0.0


 